'''
this module contains the differential-geometry definitions
for a one-dimensional manifold parameterized with a coordinate x^1 which is the arc-length, see "Lagrangian approach"
'''

from fenics import *
import ufl as ufl
import numpy as np

epsilon = ufl.PermutationSymbol(2)

# definition of scalar, vectorial and tensorial quantities
# latin indexes run on 2d curvilinear coordinates
i, j, k, l = ufl.indices(4)


def ufl_norm(x):
    return (sqrt(ufl.dot(x, x)))


'''
vector tangent to the curvilinear coordinate x on the manifold
e(psi) = {e_1}_{Lagrangian approach}

Input values: 
- 'psi': the angle psi_here = psi_{Lagrangian approach}
Return values:
- the vector e(psi)[i]
'''


def e(psi):
    return as_tensor([[cos(psi), -sin(psi)]])


'''
normal vector to the manifold
Inout values: 
- 'psi': the angle psi_here = psi_{Lagrangian approach}
Return values: 
- the normal vector n[i], a vector with two components
'''


def normal(psi):
    v = as_tensor(-epsilon[i, j] * e(psi)[0, j], (i))
    return as_tensor(v[i] / ufl_norm(v), (i))


# two-covariant metric tensor: g_{ij}
def g(psi):
    return as_tensor(e(psi)[i, k] * e(psi)[j, k], (i, j))


# two-contravariant metric tensor: g^{ij}
def g_c(psi):
    return ufl.inv(g(psi))


# determinant of the two-covariant metric tensor
def detg(psi):
    return ufl.det(g(psi))


# absolute value of the two-covariant metric tensor
def abs_detg(psi):
    return np.abs(ufl.det(g(psi)))


# square root of the determinant of the two-covariant metric tensor
def sqrt_detg(psi):
    return sqrt(detg(psi))


# square root of the absolute value of the two-covariant metric tensor
def sqrt_abs_detg(psi):
    return sqrt(abs_detg(psi))


# first fundamental form: b(z)[i,j] = b_{ij}_{al-izzi2020shear}
def b(psi):
    return as_tensor((normal(psi))[k] * (e(psi)[i, k]).dx(j), (i, j))


# mean curvature, H = H_{al-izzi2020shear}
def H(omega):
    return (0.5 * g_c(omega)[i, j] * b(omega)[j, i])


# gaussian curvature: K = K_{al-izzi2020shear}
def K(psi):
    return 0


# Christoffel symbols of the second kind related to g: Gamma(omega)[i,j,k] = {\Gamma^i_{jk}}_{al-izzi2020shear}
def Gamma(omega):
    return as_tensor(0.5 * g_c(omega)[i, l] * ((g(omega)[l, k]).dx(j) + (g(omega)[j, l]).dx(k) - (g(omega)[j, k]).dx(l)), (i, j, k))


# covariant derivative of vector v with respect to \partial/partial x and with respect to the Levi-Civita connection generated by g: Nabla_v(v, omega)[i, j] = {\Nabla_j v^i}_{al-izzi2020shear}
def Nabla_v(u, omega):
    return as_tensor((u[i]).dx(j) + u[k] * Gamma(omega)[i, k, j], (i, j))


# covariant derivative of one-form f with respect to \partial/partial x and with respect to the Levi-Civita connection generated by g: Nabla_f(f, omega)[i, j] = {\Nabla_j f_i}_{al-izzi2020shear}
def Nabla_f(f, omega):
    return as_tensor((f[i]).dx(j) - f[k] * Gamma(omega)[k, i, j], (i, j))


# covariant derivative of a two-coavariant tensor t: Nabla_ff(t, omega)[i, j, k] = \Nabla_k t_{ij}
def Nabla_ff(t, omega):
    return as_tensor((t[i, j]).dx(k) - t[l, j] * Gamma(omega)[l, i, k] - t[i, l] * Gamma(omega)[l, j, k], (i, j, k))


# lalplace-beltrami operator applied to a scalar function f : Nabla_LB(f, omega) = \Nabla_{LB} f_notes
def Nabla_LB(f, omega):
    return (- 1.0 / sqrt_detg(omega) * ((sqrt_detg(omega) * g_c(omega)[i, j] * (f.dx(j))).dx(i)))


# 2-covariant rate-of_deformation tensor for zero normal velocity: d(u, z)[i, j] = {d_{ij}}_{alizzi2020shear for zero w}
def d(v, w, omega):
    return as_tensor(0.5 * (g(omega)[i, k] * Nabla_v(v, omega)[k, j] + g(omega)[j, k] * Nabla_v(v, omega)[k, i]) - (b(omega)[i, j]) * w, (i, j))


# 2-contravariant rate-of_deformation tensor: d_c(u, un, z)[i, j] = {d^{ij}}_{alizzi2020shear}
def d_c(v, w, omega):
    return as_tensor(g_c(omega)[i, k] * g_c(omega)[j, l] * d(v, w, omega)[k, l], (i, j))


# given a vector and a scalar, return the vector vector^i * scalar
def vector_times_scalar(vector, scalar):
    return as_tensor(scalar * vector[i], (i))
