import command as cmd
import input_output as io
from command import run_command

'''
performs a test for a given variational problem and mesh choice, by comparing the solution of the mesh generation and of the variational problem on the mesh above
Input values: 
- 'commit_a', 'commit_b': the commits (or branch names) across which the test will be done
- 'root_path': the root path, upstream of all paths
- 'mesh_path_a (b)': the path of the code which generates the mesh in commit a (b)
- 'code_path_a (b)': the path of the code which solves the variational problem in commit a (b)
- 'mesh_solution_path_a', 'problem_solution_path_a', 'mesh_solution_path_b', 'problem_solution_path_b': the parhs where the mesh and variational-problem solution will be stored, for commit_a and commit_b
- 'name_of_generate_mesh': the name of the code which generates the mesh, without '.py': for example: 'generate_mesh'...
- 'problem_a', 'problem_b: the name of the variational problem to be solved in 'commit_a' and 'commit_b', respectively, for example, 'square_a', 'ring_2', ... 
- 'success': A list with only one boolean enty, whose first entry will be set to True (False) if all commands in the method call have run successfully or not, respectively. If success[0] = False, this method will do nothing and return False
Output values: 
- 'True' ('False') if all csv files generated by commit_a are the same as those generated by commit_b
'''


def test_generate_mesh_and_solve(commit_a,
                                 commit_b,
                                 root_path,
                                 mesh_path_a, code_path_a,
                                 mesh_path_b, code_path_b,
                                 mesh_solution_path_a, problem_solution_path_a,
                                 mesh_solution_path_b, problem_solution_path_b,
                                name_of_generate_mesh_a, name_of_generate_mesh_b,
                                 mesh_parameters_path_a, mesh_parameters_path_b,
                                 problem_a, problem_b,
                                 success
                                 ):
    if (success[0]):
        # this method has been called with a success variable previously set to True -> The previous checks have been performed with no errors -> Proceed with this check

        # 1 checkout commit_a, generate the mesh and solve the problem
        cmd.checkout(commit_a, success)

        # 1.1 generate the mesh
        # 1.1.1 copy mesh_parameters.csv
        run_command(f'cp {mesh_path_a}/mesh_parameters.csv {mesh_solution_path_a}/../', success)
        # 1.1.2 run mesh-generation code
        run_command(f'cd {mesh_path_a}; rm -rf {mesh_solution_path_a}; mkdir -p {mesh_solution_path_a}; python3 {name_of_generate_mesh_a}.py {mesh_parameters_path_a} {mesh_solution_path_a}', success)

        # 1.2 solve the variational problem
        run_command(f'cd {code_path_a}; rm -rf {problem_solution_path_a}; mkdir -p {problem_solution_path_a}; python3 solve.py {problem_a} {mesh_solution_path_a} {problem_solution_path_a}', success)


        # 2 checkout commit_b, generate the mesh and solve the problem
        cmd.checkout(commit_b, success)

        # 2.1 generate the mesh
        # 2.1.1 copy mesh_parameters.csv
        run_command(f'cp {mesh_path_b}/mesh_parameters.csv {mesh_solution_path_b}/../', success)
        # 2.1.2 run mesh-generation code
        run_command(f'cd {mesh_path_b}; rm -rf {mesh_solution_path_b}; mkdir -p {mesh_solution_path_b}; python3 {name_of_generate_mesh_b}.py {mesh_parameters_path_b} {mesh_solution_path_b}', success)

        # 2.2 solve the variational problem
        run_command(f'cd {code_path_b}; rm -rf {problem_solution_path_b}; mkdir -p {problem_solution_path_b}; python3 solve.py {problem_b} {mesh_solution_path_b} {problem_solution_path_b}', success)


        # 3 compare the mesh and problem solution for commit_a and commit_b
        output_mesh, error_mesh = run_command(f'cd {root_path}; ./compare-csv-files.sh {mesh_solution_path_a} {mesh_solution_path_b}', success)
        mesh_check = (((output_mesh.strip() == "")) and ((error_mesh.strip() == "")))

        # problem_check = cmd.command_empty_err_out(f'cd {root_path}; ./compare-csv-files.sh {problem_solution_path_a} {problem_solution_path_b}')
        output_problem, error_problem = run_command(f'cd {root_path}; ./compare-csv-files.sh {problem_solution_path_a} {problem_solution_path_b}', success)
        problem_check = (((output_problem.strip() == "")) and ((error_problem.strip() == "")))

        # if check = true, then commit_a and commit_b give the same result
        check = (success[0] and mesh_check and problem_check)

        io.check_print(mesh_check, 'Mesh check OK', 'Mesh check NOT OK')
        io.check_print(problem_check, 'Problem check OK', 'Problem check NOT OK')

    else:
        # this method has been called with a success variable previously set to False -> The previous checks gave  errors -> Do not proceed with the check
        print('Stopping here.')
        check = False

    return check


'''
performs a test for solution of the mesh generation and of the 'mesh check' code problem on the generated mesh above
Input values: 
- 'commit_a', 'commit_b': the commits (or branch names) across which the test will be done
- 'root_path': the root path, upstream of all paths
- 'generate_mesh_path_a (b)': the path of the code which generates the mesh in commit a (b)
- 'mesh_check_path_a (b)': the path of the code which checks the mesh in commit a (b)
- 'generate_mesh_solution_path_a(b)' the path where the output of the 'generate mesh' code is stored for commit_a(b)
- 'mesh_check_solution_path_a(b)' the path where the output of the 'check mesh' code is stored for commit_a(b)
- 'name_of_generate_mesh': the name of the code which generates the mesh, without '.py': for example: 'generate_mesh'...
- 'name_of_check_mesh': the name of the code which checks the mesh, without '.py': for example: 'check_square_mesh'
- 'mesh_parameters_path_a(b)': the path of the 'mesh_parameters.csv' file for commit a(b)
- 'success': A list with only one boolean enty, whose first entry will be set to True (False) if all commands in the method call have run successfully or not, respectively. 
    If success[0] = False, this method will do nothing and return False
Output values: 
- 'True' ('False') if all csv files generated by commit_a are the same as those generated by commit_b
'''

def test_generate_mesh_and_check_mesh(commit_a,
                                      commit_b,
                                      root_path,
                                      generate_mesh_path_a, mesh_check_path_a,
                                      generate_mesh_path_b, mesh_check_path_b,
                                      generate_mesh_solution_path_a, mesh_check_solution_path_a,
                                      generate_mesh_solution_path_b, mesh_check_solution_path_b,
                                      name_of_generate_mesh, name_of_check_mesh,
                                      mesh_parameters_path_a, mesh_parameters_path_b,
                                      success
                                      ):
    if (success[0]):
        # this method has been called with a success variable previously set to True -> The previous checks have been performed with no errors -> Proceed with this check

        # checkout commit_a, generate the mesh and solve the problem
        cmd.checkout(commit_a, success)

        run_command(f'cd {generate_mesh_path_a}; rm -rf {generate_mesh_solution_path_a}; mkdir -p {generate_mesh_solution_path_a}; python3 {name_of_generate_mesh}.py {mesh_parameters_path_a} {generate_mesh_solution_path_a}', success)
        run_command(f'cd {mesh_check_path_a}; rm -rf {mesh_check_solution_path_a}; mkdir -p {mesh_check_solution_path_a}; python3 {name_of_check_mesh}.py {generate_mesh_solution_path_a} {mesh_check_solution_path_a}', success)

        # checkout commit_b, generate the mesh and solve the problem
        cmd.checkout(commit_b, success)

        run_command(f'cd {generate_mesh_path_b}; rm -rf {generate_mesh_solution_path_b}; mkdir -p {generate_mesh_solution_path_b}; python3 {name_of_generate_mesh}.py {mesh_parameters_path_b} {generate_mesh_solution_path_b}', success)
        run_command(f'cd {mesh_check_path_b}; rm -rf {mesh_check_solution_path_b}; mkdir -p {mesh_check_solution_path_b}; python3 {name_of_check_mesh}.py {generate_mesh_solution_path_b} {mesh_check_solution_path_b}', success)

        # compare the mesh and problem solution for commit_a and commit_b
        output_generate_mesh, error_generate_mesh = run_command(f'cd {root_path}; ./compare-csv-files.sh {generate_mesh_solution_path_a} {generate_mesh_solution_path_b}', success)
        generate_mesh_check = (((output_generate_mesh.strip() == "")) and ((error_generate_mesh.strip() == "")))

        # problem_check = cmd.command_empty_err_out(f'cd {root_path}; ./compare-csv-files.sh {problem_solution_path_a} {problem_solution_path_b}')
        output_check_mesh, error_check_mesh = run_command(f'cd {root_path}; ./compare-csv-files.sh {mesh_check_solution_path_a} {mesh_check_solution_path_b}', success)
        check_mesh_check = (((output_check_mesh.strip() == "")) and ((error_check_mesh.strip() == "")))

        # if check = true, then commit_a and commit_b give the same result
        check = (success[0] and generate_mesh_check and check_mesh_check)

        io.check_print(generate_mesh_check, 'Mesh generation: check OK', 'Mesh generation: check NOT OK')
        io.check_print(check_mesh_check, 'Mesh check: check OK', 'Mesh check: check NOT OK')

    else:
        # this method has been called with a success variable previously set to False -> The previous checks gave  errors -> Do not proceed with the check
        print('Stopping here.')
        check = False

    return check