'''
This code checks the mesh generated by generate_two_squares_no_circle_mesh a

Run with
    clear; clear; python3 check_mesh.py [path where to find the mesh]
Example:
    clear; clear; python3 check_mesh.py solution
'''

import importlib
import sys

# add the path where to find the shared modules
module_path = '/home/fenics/shared/modules'
sys.path.append(module_path)

import mesh.load as lmsh
import mesh.utils as msh
rmsh = importlib.import_module('mesh.read.two_squares_no_circle')


import mesh.check_tags.two_squares_no_circle
msh.check_mesh_symmetry(lmsh.mesh, [rmsh.parameters["L"]/2, rmsh.parameters["h"]/2])

