'''
This code generates a 2d mesh (A) given by a square with a circular hole, plus a one-dimensional mesh (B) given by a line. The line mesh B corresponds to the circular boundary of A, stretched on a line. The circular hole in A is generated by successive rotations. 

Run it with
    python3 generate_mesh.py [path where to read parameters] [output directory]
Example:
    clear; clear; PARAMETERS_PATH="/home/fenics/shared/generate_mesh/2d/square/line/"; SOLUTION_PATH="/home/fenics/shared/generate_mesh/2d/square/line/solution"; rm -rf $SOLUTION_PATH; mkdir $SOLUTION_PATH; python3 generate_mesh.py $PARAMETERS_PATH $SOLUTION_PATH
'''

import meshio
import numpy as np
import gmsh
import os
import warnings
from fenics import *
import sys

# add the path where to find the shared modules
module_path = '/home/fenics/shared/modules'
sys.path.append(module_path)

import input_output as io
import mesh.utils as msh
import runtime_arguments_generate_mesh as rarg
import parameters.read.mesh as rpam

print(f'parameter_directory: {rarg.args.parameter_directory}\noutput_directory: {rarg.args.output_directory}')

output_directory = io.add_trailing_slash(rarg.args.output_directory)

mesh_file = os.path.join(output_directory, "mesh.msh") 

# write into metadata the file format wich which the mesh will be written
metadata = rpam.parameters.copy()
metadata['file_format'] = 'xdmf'


warnings.filterwarnings("ignore")
gmsh.initialize()

gmsh.model.add("my model")


delta_theta = 2 * np.pi / rpam.parameters["N"]


def R(theta):
    return np.array([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])
# sign

x_0 = np.array([rpam.parameters["r"] + rpam.parameters["resolution"], 0])



print("Starting loop over circle ... ")
for i in range(rpam.parameters["N"]):

    Q_x_r = R(i * delta_theta).dot(x_0)

    p_r = gmsh.model.occ.addPoint(Q_x_r[0], Q_x_r[1], 0)
    gmsh.model.occ.synchronize()

    line_r_R = gmsh.model.occ.addLine(p_r, p_R)
    gmsh.model.occ.synchronize()

    gmsh.model.mesh.embed(1, [line_r_R], 2, ring[0][0][0])
    gmsh.model.occ.synchronize()
print("... done.")

# add 2-dimensional objects
surfaces = gmsh.model.occ.getEntities(dim=2)
assert surfaces == ring[0]
disk_subdomain_id = 1

gmsh.model.addPhysicalGroup(surfaces[0][0], [surfaces[0][1]], disk_subdomain_id)
gmsh.model.setPhysicalName(surfaces[0][0], disk_subdomain_id, "disk")

# add 1-dimensional objects
lines = gmsh.model.occ.getEntities(dim=1)
circle_r_subdomain_id = 2
circle_R_subdomain_id = 3
# line_p_1_p_2_subdomain_id = 3

gmsh.model.addPhysicalGroup(lines[0][0], [lines[0][1]], circle_r_subdomain_id)
gmsh.model.setPhysicalName(lines[0][0], circle_r_subdomain_id, "circle_r")
gmsh.model.addPhysicalGroup(lines[1][0], [lines[1][1]], circle_R_subdomain_id)
gmsh.model.setPhysicalName(lines[1][0], circle_R_subdomain_id, "circle_R")

# add 0-dimensional objects
vertices = gmsh.model.occ.getEntities(dim=0)

# set the resolution
distance = gmsh.model.mesh.field.add("Distance")
gmsh.model.mesh.field.setNumbers(distance, "FacesList", [surfaces[0][0]])

threshold = gmsh.model.mesh.field.add("Threshold")
gmsh.model.mesh.field.setNumber(threshold, "IField", distance)
gmsh.model.mesh.field.setNumber(threshold, "LcMin", rpam.parameters["resolution"])
gmsh.model.mesh.field.setNumber(threshold, "LcMax", rpam.parameters["resolution"])
gmsh.model.mesh.field.setNumber(threshold, "DistMin", 0.5 * rpam.parameters["r"])
gmsh.model.mesh.field.setNumber(threshold, "DistMax", rpam.parameters["r"])

circle_r_dist = gmsh.model.mesh.field.add("Distance")
circle_r_threshold = gmsh.model.mesh.field.add("Threshold")

gmsh.model.mesh.field.setNumber(circle_r_threshold, "IField", circle_r_dist)
gmsh.model.mesh.field.setNumber(circle_r_threshold, "LcMin", rpam.parameters["resolution"])
gmsh.model.mesh.field.setNumber(circle_r_threshold, "LcMax", rpam.parameters["resolution"])
gmsh.model.mesh.field.setNumber(circle_r_threshold, "DistMin", 0.1)
gmsh.model.mesh.field.setNumber(circle_r_threshold, "DistMax", 0.5)

minimum = gmsh.model.mesh.field.add("Min")
gmsh.model.mesh.field.setNumbers(minimum, "FieldsList", [threshold, circle_r_threshold])
gmsh.model.mesh.field.setAsBackgroundMesh(minimum)

gmsh.model.occ.synchronize()
gmsh.model.mesh.generate(2)
gmsh.write(mesh_file)

msh.print_mesh_lines_to_csv(mesh_file, output_directory + 'line_vertices.csv')

mesh_from_file = meshio.read(mesh_file)

msh.full_write(mesh_file, ['triangle', 'line'], metadata, output_directory, True)
