'''
This code generates a 2d mesh (A) given by a square with a circle (the circle is meshed inside), plus a one-dimensional mesh (B) given by a line. The line mesh B corresponds to the circular boundary of A, stretched on a line. The circle in A is generated by successive rotations. 

Run it with
    python3 generate_mesh.py [path where to read parameters] [output directory]
Example:
    clear; clear; PARAMETERS_PATH="/home/fenics/shared/generate_mesh/2d/square/line/"; SOLUTION_PATH="/home/fenics/shared/generate_mesh/2d/square/line/solution"; rm -rf $SOLUTION_PATH; mkdir $SOLUTION_PATH; python3 generate_mesh.py $PARAMETERS_PATH $SOLUTION_PATH
'''

from fenics import *
import gmsh
import numpy as np
import os
import pygmsh
import sys

# add the path where to find the shared modules
module_path = '/home/fenics/shared/modules'
sys.path.append(module_path)

import calculus as cal
import input_output as io
import mesh.utils as msh
import runtime_arguments_generate_mesh as rarg
import parameters.read.mesh as rpam

print(f'parameter_directory: {rarg.args.parameter_directory}\noutput_directory: {rarg.args.output_directory}')

output_directory = io.add_trailing_slash(rarg.args.output_directory)

mesh_file = os.path.join(rarg.args.output_directory, "mesh.msh")

# write into metadata the file format wich which the mesh will be written
metadata = rpam.parameters.copy()
metadata['file_format'] = 'xdmf'

print("output_directory = ", rarg.args.output_directory)

geometry = pygmsh.occ.Geometry()
model = geometry.__enter__()




#1. add  square


square_p_bl = gmsh.model.geo.addPoint(0, 0, 0)
square_p_br = gmsh.model.geo.addPoint(rpam.parameters["L"], 0, 0)
square_p_tr = gmsh.model.geo.addPoint(rpam.parameters["L"], rpam.parameters["h"], 0)
square_p_tl = gmsh.model.geo.addPoint(0, rpam.parameters["h"], 0)
gmsh.model.geo.synchronize()

square_line_b = gmsh.model.geo.addLine(square_p_bl, square_p_br)
square_line_r = gmsh.model.geo.addLine(square_p_br, square_p_tr)
square_line_t = gmsh.model.geo.addLine(square_p_tr, square_p_tl)
square_line_l = gmsh.model.geo.addLine(square_p_tl, square_p_bl)
gmsh.model.geo.synchronize()

square_loop = gmsh.model.geo.addCurveLoop([square_line_b, square_line_r, square_line_t, square_line_l])
gmsh.model.geo.synchronize()


#2. add circle

# angular fraction corresponding to each segment of the circle
delta_theta = 2 * np.pi / rpam.parameters["N"]

circle_coordinates = [np.array([rpam.parameters["c_r"][0] + rpam.parameters['r'], rpam.parameters['c_r'][1]])]
circle_points = [gmsh.model.geo.addPoint(circle_coordinates[0][0], circle_coordinates[0][1], 0)]
gmsh.model.geo.synchronize()

circle_lines = []

print(f'added point with coordinates {circle_coordinates[-1]}')


print("Starting loop over circle ... ")
for i in range(1, rpam.parameters["N"]):

    circle_coordinates.append(
        np.add(rpam.parameters['c_r'], cal.R(i * delta_theta).dot(np.subtract(circle_coordinates[0], rpam.parameters['c_r'])))
        )

    circle_points.append(gmsh.model.geo.addPoint(circle_coordinates[-1][0], circle_coordinates[-1][1], 0))
    gmsh.model.geo.synchronize()

    circle_lines.append(gmsh.model.geo.addLine(circle_points[-2], circle_points[-1]))
    gmsh.model.geo.synchronize()

    print(f'added point with coordinates {circle_coordinates[-1]}')

print("... done.")

circle_lines.append(gmsh.model.geo.addLine(circle_points[-1], circle_points[0]))
gmsh.model.geo.synchronize()



circle_loop = gmsh.model.geo.addCurveLoop(circle_lines)
gmsh.model.geo.synchronize()

square_minus_circle_surface = gmsh.model.geo.addPlaneSurface([square_loop, circle_loop])
gmsh.model.geo.synchronize()

gmsh.model.mesh.embed(1, circle_lines, 2, square_minus_circle_surface)
gmsh.model.geo.synchronize()

circle_surface = gmsh.model.geo.addPlaneSurface([circle_loop])
gmsh.model.geo.synchronize()



# add 1-dimensional objects
lines = gmsh.model.getEntities(dim=1)

# add square lines
gmsh.model.addPhysicalGroup(lines[0][0], [lines[0][1]], rpam.parameters["line_sub_mesh_1_b_id"])
gmsh.model.setPhysicalName(lines[0][0], rpam.parameters["line_sub_mesh_1_b_id"], "square_line_b")

gmsh.model.addPhysicalGroup(lines[1][0], [lines[1][1]], rpam.parameters["line_sub_mesh_1_r_id"])
gmsh.model.setPhysicalName(lines[1][0], rpam.parameters["line_sub_mesh_1_r_id"], "square_line_r")

gmsh.model.addPhysicalGroup(lines[2][0], [lines[2][1]], rpam.parameters["line_sub_mesh_1_t_id"])
gmsh.model.setPhysicalName(lines[2][0], rpam.parameters["line_sub_mesh_1_t_id"], "square_line_t")

gmsh.model.addPhysicalGroup(lines[3][0], [lines[3][1]], rpam.parameters["line_sub_mesh_1_l_id"])
gmsh.model.setPhysicalName(lines[3][0], rpam.parameters["line_sub_mesh_1_l_id"], "square_line_l")

#add circle lines
gmsh.model.addPhysicalGroup(1, [lines[i][1] for i in range(4, 4 + rpam.parameters['N'])], rpam.parameters["circle_loop_id"])
gmsh.model.setPhysicalName(1, rpam.parameters["circle_loop_id"], "circle_loop")


# add 2-dimensional objects
surfaces = gmsh.model.getEntities(dim=2)

gmsh.model.addPhysicalGroup(surfaces[0][0], [surfaces[0][1]], rpam.parameters["sub_mesh_1_id"])
gmsh.model.setPhysicalName(surfaces[0][0], rpam.parameters["sub_mesh_1_id"], "square_minus_circle_surface")

gmsh.model.addPhysicalGroup(surfaces[1][0], [surfaces[1][1]], rpam.parameters["sub_mesh_0_id"])
gmsh.model.setPhysicalName(surfaces[1][0], rpam.parameters["sub_mesh_0_id"], "circle_surface")



# set the resolution
# se resolution equal to parameters["resolution"] at a distance 0 from surface_in, and  at distance max(rpam.parameters["L"],rpam.parameters["h"]) from sub_mesh_1_id
distance = gmsh.model.mesh.field.add("Distance")

gmsh.model.mesh.field.setNumbers(distance, "FacesList", [circle_loop])

threshold = gmsh.model.mesh.field.add("Threshold")
gmsh.model.mesh.field.setNumber(threshold, "IField", distance)
gmsh.model.mesh.field.setNumber(threshold, "LcMin", rpam.parameters["resolution"])
gmsh.model.mesh.field.setNumber(threshold, "LcMax", rpam.parameters["resolution"])
gmsh.model.mesh.field.setNumber(threshold, "DistMin", 0)
gmsh.model.mesh.field.setNumber(threshold, "DistMax", max(rpam.parameters["L"], rpam.parameters["h"]))


minimum = gmsh.model.mesh.field.add("Min")
gmsh.model.mesh.field.setNumbers(minimum, "FieldsList", [threshold])
gmsh.model.mesh.field.setAsBackgroundMesh(minimum)

gmsh.model.geo.synchronize()

geometry.generate_mesh(dim=2)
gmsh.write(mesh_file)

msh.full_write(mesh_file, ['triangle', 'line'], metadata, output_directory, True)

msh.generate_sub_mesh(output_directory, os.path.join(output_directory, 'sub_meshes', 'in'), rpam.parameters["sub_mesh_0_id"])
msh.generate_sub_mesh(output_directory, os.path.join(output_directory, 'sub_meshes', 'out'), rpam.parameters["sub_mesh_1_id"])


# print the boundary points of the boundary given by the and circle
msh.sorted_boundary_points(
    msh.read_mesh(os.path.join(output_directory, 'triangle_mesh.xdmf')), 
    output_directory, 
    [rpam.parameters['circle_loop_id']],
    os.path.join(output_directory, 'boundary_points_id_' + str(rpam.parameters['circle_loop_id']) + '.csv'))

model.__exit__()