'''
This code reads the box mesh generated by ~/shared/generate_mesh/3d/box/generate_mesh.py
and creates a submesh of it, i.e., a sphere mesh given by the boundary of the box

Run with
    clear; clear; python3 generate_submesh_box.py [path where to find the box mesh] [path where to store the submesh]
Example:
    clear; clear; python3 generate_submesh_box.py /home/fenics/shared/generate_mesh/3d/box/solution  /home/fenics/shared/generate_mesh/3d/submesh_box/solution
'''


import colorama as col
from fenics import *
import meshio
import numpy as np
import sys

#add the path where to find the shared modules
module_path = '/home/fenics/shared/modules'
sys.path.append(module_path)

import calculus as cal
import geometry as geo
import input_output as io
import load_mesh as lmsh
import mesh as msh
import runtime_arguments as rarg

output_directory = io.add_trailing_slash(rarg.args.output_directory)


# radius of the smallest cell in the mesh
r_mesh = lmsh.mesh.hmin()

parameters = io.read_parameters_from_csv_file(rarg.args.input_directory + "/mesh_metadata.csv")


#read the mesh of the cube
box_mesh = Mesh()
xdmf = XDMFFile(box_mesh.mpi_comm(), (rarg.args.input_directory) + "/tetra_mesh.xdmf")
xdmf.read(box_mesh)


#extract the mesh corresponding to the side of the cube with y = 0 and store it in mesh2D
with XDMFFile(output_directory + "cube_mesh.xdmf") as xdmf:
    xdmf.write(box_mesh)

mesh_dimension=3
boundary_mesh_dimension = mesh_dimension - 1
cube_mesh = BoundaryMesh(box_mesh, "exterior")
print("Dimension of boundary_mesh = ", box_mesh.geometry().dim())

mapping = cube_mesh.entity_map(boundary_mesh_dimension)
part_of_cube_side = MeshFunction("size_t", cube_mesh, boundary_mesh_dimension)
#run over all cells of boundary_mesh and write `1` in part_of_cube_side for the cells which have the y component of the facet normal equal to -1 : in this way, one is selecting the cells which belong to the xz side of the box
for cell in cells(cube_mesh):
    curr_facet_normal = Facet(box_mesh, mapping[cell.index()]).normal()
    if near(curr_facet_normal.y(), -1.0):  # On cube_side boundary
        part_of_cube_side[cell] = 1

cube_side_boundary = SubMesh(cube_mesh, part_of_cube_side, 1)
#File('cube_side_boundary.pvd') << cube_side_boundary
with XDMFFile(output_directory + "cube_side_mesh.xdmf") as xdmf:
    xdmf.write(cube_side_boundary)


in_mesh = meshio.read(output_directory + "cube_side_mesh.xdmf")

cells = in_mesh.get_cells_type("triangle")
#remove the y component of the points in in_mesh to switch from a 3d to a 2d mesh
points = np.delete(in_mesh.points, 1, axis=1)
out_mesh = meshio.Mesh(points=points, cells={"triangle": cells})
meshio.write(output_directory + "pruned_mesh.xdmf", out_mesh)

#the resulting 2d mesh is written into mesh2D
mesh2D = Mesh()
with XDMFFile(output_directory + "pruned_mesh.xdmf") as xdmf:
    xdmf.read(mesh2D)
print("Dimension of mesh2D = ", mesh2D.geometry().dim())

'''
#test mesh2D by integrating a function over it 
#analytical expression for a  scalar function used to test the ds
class FunctionTestIntegral(UserExpression):
    def eval(self, values, x):
        values[0] = (np.cos(x[0]-x[1]))**2 * (np.sin(x[0]-x[1]))**3
    def value_shape(self):
        return (1,)

#read the tetrahedra
mvc = MeshValueCollection("size_t", mesh2D, mesh2D.topology().dim())
# with XDMFFile(output_directory + "pruned_mesh.xdmf") as infile:
#     infile.read(mvc, "name_to_read")
cf = cpp.mesh.MeshFunctionSizet(mesh2D, mvc)
# xdmf.close()
dv_custom = Measure("dx", domain=mesh2D, subdomain_data=cf)    # Line measure

Q = FunctionSpace( mesh2D, 'P', 1 )
f_test_ds = Function( Q )

# f_test_ds is a scalar function defined on the mesh, that will be used to test whether the boundary elements ds_circle, ds_inflow, ds_outflow, .. are defined correclty . This will be done by computing an integral of f_test_ds over these boundary terms and comparing with the exact result
f_test_ds.interpolate( FunctionTestIntegral( element=Q.ufl_element() ))

#print out the integrals on the surface elements and compare them with the exact values to double check that the elements are tagged correctly
print(f"Volume = {assemble(f_test_ds*dv_custom)}, should be 0.0219446")

test_mesh_integral_errors = []

test_mesh_integral_errors.append(msh.test_mesh_integral( 0.0219446, f_test_ds, dv_custom, 'Volume' ))

print(f'Maximum relative error of mesh integrals = {col.Fore.RED}{max(test_mesh_integral_errors):.{io.number_of_decimals}e}{col.Fore.RESET}')

'''